package constant

const (
	PRODUCT_TYPE_C2C = "C2C"
	PRODUCT_TYPE_CRL = "CRL"
)

const (
	BUCKET_1_MIN_DPD = 1
	BUCKET_1_MAX_DPD = 30
	BUCKET_2_MIN_DPD = 31
	BUCKET_2_MAX_DPD = 60
	BUCKET_3_MIN_DPD = 61
	BUCKET_3_MAX_DPD = 90
	BUCKET_4_MIN_DPD = 121
	BUCKET_4_MAX_DPD = 150
)
